//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latex2CD2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"\documentclass[pdflatex,12pt,a4paper]{report}
\usepackage{amsmath} 
\usepackage{bbm} 
\usepackage{commath} 
\usepackage{textcomp} 
\usepackage{sistyle} 
\usepackage{bigstrut} 
\usepackage{ae,aecompl} 
\newcommand{\boldm}[1]{\mbox{\boldmath{$\mathrm {#1}$}}}
\def \b#1{\relax \ifmmode{\boldm {#1}\/}\else{$\bf {#1}\/$}\fi}
\begin{document} 
\thispagestyle{empty}
%%ANCHOR%%
\end{document}
")]
        public string DefaultTemplate {
            get {
                return ((string)(this["DefaultTemplate"]));
            }
            set {
                this["DefaultTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTemplate {
            get {
                return ((string)(this["LastTemplate"]));
            }
            set {
                this["LastTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mgs.exe")]
        public string GSPath {
            get {
                return ((string)(this["GSPath"]));
            }
            set {
                this["GSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdflatex.exe")]
        public string PDFLatexPath {
            get {
                return ((string)(this["PDFLatexPath"]));
            }
            set {
                this["PDFLatexPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hideWindows {
            get {
                return ((bool)(this["hideWindows"]));
            }
            set {
                this["hideWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showLog {
            get {
                return ((bool)(this["showLog"]));
            }
            set {
                this["showLog"] = value;
            }
        }
    }
}
